### ISSUE TITLE
Not updated to Rimworld 1.1

### ISSUE THREAD

**Issue by Stretop** [LegendaryMinuteman/PlanetsidePoliticsandReligions#1]
Hi, LegendaryMinuteman. On Steam and Ludeon forums your mod is shown as updated to 1.1, but here it seems that the mod is still not updated. Is any update planned?

**Comment by LegendaryMinuteman** [comment]
I am working on it now, check back soon.

**Comment by LegendaryMinuteman** [comment]
Updated.
